version: '3.8'

services:
  casafrontend:
    container_name: casafrontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_PASSWORD: ${NEXT_PUBLIC_PASSWORD}
    image: casafrontend:latest
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_PASSWORD: ${NEXT_PUBLIC_PASSWORD}
    restart: unless-stopped