
services:
  # ===== BASE DE DONNÉES =====
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_NAME}
    volumes:
      - ./bdd/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mariadb_data:/var/lib/mysql
    networks:
      casa_network:
        ipv4_address: 172.20.0.2
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p${MARIADB_PASSWORD}"]
      timeout: 20s
      retries: 10
      start_period: 40s
    restart: always

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 4000:3000
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: ${MARIADB_PORT}
      MB_DB_USER: ${MARIADB_USER}
      MB_DB_PASS: ${MARIADB_PASSWORD}
      MB_DB_HOST: mariadb
    networks:
      casa_network:
        ipv4_address: 172.20.0.7
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

  # ===== BACKUP DE LA BASE DE DONNÉES =====
  mariadb-backup:
    image: alpine:3.19
    container_name: mariadb-backup
    environment:
      DB_HOST: mariadb
      DB_PORT: ${MARIADB_PORT}
      DB_NAME: ${MARIADB_NAME}
      DB_USER: ${MARIADB_USER}
      DB_PASS: ${MARIADB_PASSWORD}
      TZ: Europe/Paris
    volumes:
      - /home/casamur/backups:/backups  # Dossier pour stocker les backups
      - /home/casamur/scripts:/scripts:ro  # Scripts en lecture seule
    command: >
      sh -c "
        apk add --no-cache mariadb-client tzdata &&
        echo '0 2 * * * /scripts/backup_mariadb.sh >/dev/null 2>&1' > /var/spool/cron/crontabs/root &&
        chmod 0644 /var/spool/cron/crontabs/root &&
        crond -f -L /var/log/cron.log
      "
    networks:
      casa_network:
        ipv4_address: 172.20.0.6
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped


  # ===== PHPMYADMIN =====
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${MARIADB_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      casa_network:
        ipv4_address: 172.20.0.3
    restart: unless-stopped

  # ===== BACKEND =====
  backend:
    image: casabackend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: casabackend
    ports:
      - "5000:5000"
    environment:
      # Variables depuis le .env racine
      DB_HOST: mariadb
      DB_PORT: ${MARIADB_PORT}
      DB_PASSWORD: ${MARIADB_PASSWORD}
      DB_NAME: ${MARIADB_NAME}
      DB_USER: ${MARIADB_USER}
      ENV: prod
    volumes:
      - /home/casamur/data/signatures:/code/static/uploads/signatures
    networks:
      casa_network:
        ipv4_address: 172.20.0.4
    depends_on:
      mariadb:
        condition: service_healthy

  # ===== FRONTEND =====
  frontend:
    image: casafrontend:latest
    container_name: casafrontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL_PROD=${NEXT_PUBLIC_API_URL_PROD}
        - NEXT_PUBLIC_PASSWORD=${NEXT_PUBLIC_PASSWORD}
        - NEXT_PUBLIC_ENV=prod
    ports:
      - "3000:3000"
    networks:
      casa_network:
        ipv4_address: 172.20.0.5
    depends_on:
      - backend

volumes:
  mariadb_data:
    driver: local

networks:
  casa_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
