services:
  backend:
    image: casabackend
    build: .
    container_name: casabackend
    ports:
      - "5000:5000"
    networks:
      casabdd:
        ipv4_address: 172.16.63.3
    env_file:
      - .env
    volumes:
      - /home/casamur/data/signatures:/code/static/uploads/signatures
    restart: unless-stopped

networks:
  casabdd:
    external: true
